#pragma once

/*STALE KLAWISZOWE*/
#define ESC 0x1b
#define ARROW_UP 0x48
#define ARROW_DOWN 0x50
#define ARROW_LEFT 0x4b
#define ARROW_RIGHT 0x4d
#define ENTER 0x0d
#define BACKSPACE 0x08;

/*STALE INTERFEJSU*/
#define WINDOW_TITLE 0
#define EXIT_INFO 1
#define MOVE_INFO 2
#define CHANGE_TEXT_COLOR_INFO 3
#define CHANGE_BACKGROUND_COLOR_INFO 4
#define DRAW_LINE_INFO 5
#define CHOSE_TEXT_COLOR_INFO 6

/*STALE KURSORA*/
#define MIN_X_POSITION 1
#define MAX_X_POSITION 120
#define MIN_Y_POSITION 6
#define MAX_Y_POSITION 30

/*STALA STOSTU*/
#define DEFAULT_STACK_SIZE 100

/*STALE BMP*/
#define BMP_HEADER 54
#define BMP_WIDTH_INFO 18
#define BMP_HEIGHT_INFO 22
#define COLORS_PER_PIXEL 3
#define BMP_R_POSITION 2
#define BMP_G_POSITION 1
#define BMP_B_POSITION 0

#define NUMBER_OF_COLORS 16