#pragma once

/*STALE KLAWISZOWE*/
#define ESC 0x1b
#define ARROW_UP 0x48
#define ARROW_DOWN 0x50
#define ARROW_LEFT 0x4b
#define ARROW_RIGHT 0x4d
#define ENTER 0x0d
#define BACKSPACE 0x08
#define PAGEUP 0x49
#define PAGEDOWN 0x51
#define DELETE 0x53

/*STALE INTERFEJSU*/
#define UI_ELEMENTS 22
#define FILE_NAME_INFO 1
#define EXIT_INFO 2
#define MOVE_INFO 3
#define DRAW_LINE_INFO 4
#define DRAW_RECTANGLE_INFO 5
#define CHOSE_COLOR_INFO 6
#define SAVE_FILE_INFO 7
#define LOAD_DEFAULT_FILE_INFO 8
#define LOAD_FILE_INFO 9
#define CREATE_NEW_FILE_INFO 10
#define UNDO_INFO 11
#define PREV_FILE_INFO 12
#define NEXT_FILE_INFO 13
#define CURSOR_X_POSITION_INFO 14
#define CURSOR_Y_POSITION_INFO 15
#define MODE_INFO 16
#define LINE_MODE_INFO 17
#define RECTANGLE_MODE_INFO 18
#define QUESTION 21
#define INPUT_FILE_NAME 22
#define INPUT_FILE_WIDTH 23
#define INPUT_FILE_HEIGHT 24

#define UI_X_POSITION 1

/*STALE KURSORA*/
#define MIN_X_POSITION 38
#define MAX_X_POSITION 120
#define MIN_Y_POSITION 2
#define MAX_Y_POSITION 30

/*STALA STOSTU*/
#define DEFAULT_STACK_SIZE 50

/*STALE BMP*/
#define BMP_HEADER 54
#define BMP_WIDTH_INFO 18
#define BMP_HEIGHT_INFO 22
#define BMP_COLORS_PER_PIXEL 3
#define BMP_R_POSITION 2
#define BMP_G_POSITION 1
#define BMP_B_POSITION 0
#define BMP_ELEMENTS_HEADER_START 2
#define BMP_ONE_ELEMENT 1
#define BMP_BYTES_HEADER_TOSKIP 4
#define BMP_OFFSET 54
#define BMP_SIZE 40
#define BMP_PLANES 1
#define BMP_BIT_COUNT 24
#define BMP_COMPRESION 0
#define BMP_RESOLUTION 2835
#define BMP_DEFAULT_COLOR_PALETTE 0
#define BMP_IMPORTANT_COLOR 0
#define BMP_PADDING 2

/*STALE XPM2*/
#define XPM_NUMBER_OF_VALUES 4
#define XPM_HEIGHT 1
#define XPM_WIDTH 0
#define XPM_COLORS 2
#define XPM_CHARACTERS_PER_PIXEL 3
#define BUFF 8

/*STALE MFF*/
#define MFF_NUMBER_OF_VALUES 3
#define MFF_HEIGHT 1
#define MFF_WIDTH 0
#define MFF_COLORS 2


#define NUMBER_OF_COLORS 16
#define MAX_FILENAME_LENGTH 10
#define DEFAULT_NUMBER_OF_FILES 10