#pragma once

/*STALE KLAWISZOWE*/
#define ESC 0x1b
#define ARROW_UP 0x48
#define ARROW_DOWN 0x50
#define ARROW_LEFT 0x4b
#define ARROW_RIGHT 0x4d
#define ENTER 0x0d
#define BACKSPACE 0x08

/*STALE INTERFEJSU*/
#define WINDOW_TITLE 0
#define EXIT_INFO 1
#define MOVE_INFO 2
#define CHANGE_TEXT_COLOR_INFO 3
#define CHANGE_BACKGROUND_COLOR_INFO 4
#define DRAW_LINE_INFO 5
#define CHOSE_TEXT_COLOR_INFO 6

/*STALE KURSORA*/
#define MIN_X_POSITION 1
#define MAX_X_POSITION 120
#define MIN_Y_POSITION 6
#define MAX_Y_POSITION 30

/*STALA STOSTU*/
#define DEFAULT_STACK_SIZE 100

/*STALE BMP*/
#define BMP_HEADER 54
#define BMP_WIDTH_INFO 18
#define BMP_HEIGHT_INFO 22
#define BMP_COLORS_PER_PIXEL 3
#define BMP_R_POSITION 2
#define BMP_G_POSITION 1
#define BMP_B_POSITION 0
#define BMP_ELEMENTS_HEADER_START 2
#define BMP_ONE_ELEMENT 1
#define BMP_BYTES_HEADER_TOSKIP 4
#define BMP_OFFSET 54
#define BMP_SIZE 40
#define BMP_PLANES 1
#define BMP_BIT_COUNT 24
#define BMP_COMPRESION 0
#define BMP_RESOLUTION 2835
#define BMP_DEFAULT_COLOR_PALETTE 0
#define BMP_IMPORTANT_COLOR 0

/*STALE XPM2*/
#define XPM_NUMBER_OF_VALUES 4
#define XPM_HEIGHT 1
#define XPM_WIDTH 0
#define XPM_COLORS 2
#define XPM_CHARACTERS_PER_PIXEL 3
#define BUFF 8

#define NUMBER_OF_COLORS 16